package org.prakash.bitmagic;
//https://www.geeksforgeeks.org/maximum-value-pair-array/
/*
Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of element from the array.
Note: AND is bitwise '&' operator.


Example 1:

Input:
N = 4
arr[] = {4, 8, 12, 16}
Output: 8
Explanation:
Pair (8,12) has the Maximum AND Value 8.
Example 2:

Input:
N = 4
arr[] = {4, 8, 16, 2}
Output: 0
Explanation: Maximum AND Value is 0.

 */
public class MaxValOfAPairInArr {

    // Return the no. of elements in arr has msb set as in given pattern
    static int checkBit(int pattern, int arr[], int n) {
        int count = 0;
        for (int i = 0; i < n; i++)
            if ((pattern & arr[i]) == pattern)
                count++;
        return count;
    }

    // Function for finding maximum and value pair
    static int maxAND(int arr[], int n) {
        int res = 0, count;

        // iterate over total of 30bits
        // from msb to lsb
        for (int bit = 31; bit >= 0; bit--) {
            // find the count of element
            // having set msb
            count = checkBit(res | (1 << bit), arr, n);

            // if count >= 2 set particular
            // bit in result
            if (count >= 2)
                res |= (1 << bit);
        }

        return res;
    }

    // driver function
    public static void main(String argc[]) {
        //int[] arr = {4, 8, 6, 2};
        int[] arr = {4, 8, 12, 16};
        int n = arr.length;
        System.out.println("Maximum AND Value = " +
                maxAND(arr, n));
    }
}
